version: '3.5'

services:
  db:
    image: postgres:alpine
    container_name: db-cross-docking
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: aseca-cross-docking
#    environment:
#      - PORT=${PORT}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - DATABASE_URL=${DATABASE_URL}
#    ports:
#      - '3001:3001'
#    depends_on:
#      - db
#    volumes:
#      - ./src:/app/src
#    command:
#      - sh
#      - -c
#      - |
#        npm run db:apply && npm run start:dev
##        && npm run db:seed

volumes:
  db-data: